version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  api:
    build: .
    ports:
      - "3001:3001" # Run tests on a different port
    depends_on:
      - db
    command: npm test # Run tests instead of starting the server
  db-init:
    build: ./db-init
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: productdb
volumes:
  db_data: {}